name: Azure Static Web Apps CI/CD
run-name: ${{github.actor}} has triggerd the build
on:
  workflow_dispatch

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true       
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@latest
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "out" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
        # env:
        #   IS_STATIC_EXPORT: true  

# Tried
# /,"",out,true
# src,"",out,true
# /src,"",out,true ->Removed src folder
# /,"","out",removed amd added next export in package.json, 
# removed src folder, corrected css path, correct tailwind.config and removes pages/api
# Add module.exports = {
#   images: {
#       unoptimized: true
#   }
# } in next.config.js

